version: '3'
services:
  engine:
    container_name: engine
    build:
      context: .
      dockerfile: dockerfiles/engine/Dockerfile
    volumes:
      - ./logs:/usr/src/app/logs
    environment:
      - PLAYER_1_NAME=bot1
      - PLAYER_2_NAME=bot2
      - PLAYER_1_WEBSOCKET_URI=ws://bot1:8765
      - PLAYER_2_WEBSOCKET_URI=ws://bot2:8765
      - PYTHONUNBUFFERED=1
    networks:
      - pokerbot_network
    depends_on:
      - bot1
      - bot2
  bot1:
    container_name: pokerbot1
    build:
      context: .
      dockerfile: dockerfiles/python_skeleton/Dockerfile
    expose:
      - "8765"
    networks:
      - pokerbot_network
    environment:
      - PYTHONUNBUFFERED=1
  bot2:
    container_name: pokerbot2
    build:
      context: .
      dockerfile: dockerfiles/python_skeleton2/Dockerfile
    expose:
      - "8765"
    networks:
      - pokerbot_network
    environment:
      - PYTHONUNBUFFERED=1

networks:
  pokerbot_network:
    name: pokerbot_network
